### ISSUE TITLE
UI scale issue when moving window between screens

### ISSUE THREAD

**Issue by fwal** [microsoft/Git-Credential-Manager-Core#408] opened 2021-08-11 08:44 UTC
**Which version of GCM Core are you using?**
`2.0.475+27fbadca1d`

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [x] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [x] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

The login UI is presented properly on both my screens.

**Actual behavior**

UI opened on laptop screen (3072 × 1920) and displayed properly but when I dragged the window over to my main monitor (3440 × 1440) it scaled the UI up so much it became unusable. The size of the window remained the same.

Everything else worked as it should so no problem signing in when using the window on the laptop screen.

Window on laptop screen
<img width="488" alt="20210811 - Frederik - GitHub UI" src="https://user-images.githubusercontent.com/650559/128997545-a0f6168d-fd71-4e60-8701-34b013499e03.png">

Window on external monitor screen
![20210811 - Frederik - GitHub UI](https://user-images.githubusercontent.com/650559/128997572-38cc1ed2-755b-438e-a826-5c33d949b37b.png)

**Logs**

Not applicable.

**Comment by ametgueye** [comment] 2021-08-14 05:07
![image](https://user-images.githubusercontent.com/88919440/129434781-3db9c85c-386f-4612-9749-0e1227198aa5.png)

**Comment by mjcheetham** [comment] 2021-10-05 14:24
Managed to reproduce the problem. The issue is with the AvaloniaUI framework itself; managed to repro this on their new project template when using Avalonia 0.10.3 (GCM uses 0.10.1). The problem appears to be fixed in Avalonia 0.10.7 (the latest at time of writing).

Will update the version of Avalonia GCM uses to 0.10.7.

**Closed** 2021-10-06 10:40 UTC
Labels: platform:osx, external, gui
