### ISSUE TITLE
Empty git config options (for example proxy config) is ignored

### ISSUE THREAD

**Issue by TobiX** [microsoft/Git-Credential-Manager-Core#476] opened 2021-10-04 10:12 UTC
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core --version` and paste the output.

2.0.498+7ad55fb809

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [x] Other - please describe

Internel GitLab, no proxy required, but connection to internet requires a proxy.

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [x] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully. I'm using this Git config:
```
[http]
	proxy = http://proxy:80
[http "https://INT.REDACTED"]
	proxy = 
```
which git understands as: Proxy for everything, except INT.REDACTED
But GCMC interprets as: Proxy for everything.

**Actual behavior**

Connection fails, GCMC tries to use the proxy for the connection.

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.
```
12:08:09.827619 ...\Application.cs:80   trace: [RunInternalAsync] Version: 2.0.498.54650
12:08:09.833660 ...\Application.cs:81   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
12:08:09.833660 ...\Application.cs:82   trace: [RunInternalAsync] Platform: Windows (x86-64)
12:08:09.834619 ...\Application.cs:83   trace: [RunInternalAsync] AppPath: C:\Program Files\Git\mingw64\libexec\git-core\git-credential-manager-core.exe
12:08:09.834619 ...\Application.cs:84   trace: [RunInternalAsync] Arguments: get
12:08:09.896316 ...GitCommandBase.cs:35 trace: [ExecuteAsync] Start 'get' command...
12:08:15.463168 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Detecting host provider for input:
12:08:15.464172 ...GitCommandBase.cs:50 trace: [ExecuteAsync] 	protocol=https
12:08:15.464172 ...GitCommandBase.cs:50 trace: [ExecuteAsync] 	host=INT.REDACTED
12:08:15.572662 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
12:08:15.574625 ...viderRegistry.cs:162 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
12:08:15.577624 ...viderRegistry.cs:154 trace: [GetProviderAsync] Querying remote URL for host provider auto-detection.
12:08:15.578628 ...pClientFactory.cs:54 trace: [CreateClient] Creating new HTTP client instance...
12:08:15.712580 ...ClientFactory.cs:151 trace: [TryCreateProxy] Created a WebProxy instance:
12:08:15.712580 ...ClientFactory.cs:152 trace: [TryCreateProxy] 	address=http://proxy/
12:08:15.712580 ...ClientFactory.cs:152 trace: [TryCreateProxy] 	useDefaultCredentials=true
12:08:15.712580 ...pClientFactory.cs:60 trace: [CreateClient] HTTP client is using the configured proxy.
```

Then, on console:
```
fatal: Fehler beim Senden der Anforderung.
fatal: Die zugrunde liegende Verbindung wurde geschlossen: F├╝r den gesch├╝tzten SSL/TLS-Kanal konnte keine Vertrauensstellung hergestellt werden..
fatal: Das Remotezertifikat ist laut Validierungsverfahren ung├╝ltig.
```

(Certificate error, because the proxy presents an untrusted certificate)

**Comment by mjcheetham** [comment] 2021-10-05 13:24
Closing as duplicate of #442. This has been fixed in #449 but has _not yet been included in a release_.

**Closed by mjcheetham** 2021-10-05 13:24 UTC
Labels: auth-issue
