### ISSUE TITLE
gcmcoreuser-win-x86 installer can be installed with non-admin permissions but not deinstalled

### ISSUE THREAD

**Issue by NEOatNHNG** [microsoft/Git-Credential-Manager-Core#290] opened 2021-02-18 11:00 UTC
The gcmcoreuser-win-x86 installer works fine without administrator privileges but when I try to uninstall it, I need to provide administrator privileges to it (discovered with release v2.0.318-beta).

Maybe have a look at https://github.com/CAcertOrg/cacert-root-cert-installer on how to create an installer that can properly handle the single-user and multi-user installation.

**Comment by mjcheetham** [comment] 2021-10-08 14:32
In my testing I am unable to reproduce the problem.. from a local, standard user account (not a member of the Administrators group) I am able to both install and uninstall the GCM Core User installation without any prompts/requirements to be an admin.

![image](https://user-images.githubusercontent.com/5658207/136575103-cd075199-fbd2-47ea-bffa-6f108642e4a1.png)
![image](https://user-images.githubusercontent.com/5658207/136575162-f683ecdf-632b-424b-aa90-862c80140e99.png)

![image](https://user-images.githubusercontent.com/5658207/136574823-d5b019f3-8745-4b1e-896b-4023bd7d724e.png)

![image](https://user-images.githubusercontent.com/5658207/136574971-5eeee6ef-d575-4bc9-b570-12062abb91eb.png)

![image](https://user-images.githubusercontent.com/5658207/136574773-7139f58d-3401-40e1-93c8-17adb5cd687e.png)

**Comment by mjcheetham** [comment] 2021-11-12 10:13
Closing as no repro.

**Closed by mjcheetham** 2021-11-12 10:13 UTC
Labels: bug, platform:windows, installation
